apiVersion: v1
kind: Service
metadata:
  name: my-app   # should match selector label in deployment
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: my-app
  type: ClusterIP # when we create a service for ingress usage, it should be of the ClusterIp, since ingress will expose it externally

